### ISSUE TITLE
subtle bug: pod status change cannot trigger Reconciler directly

### ISSUE THREAD

**Issue by TimeSea05** [OpenRHINO/RHINO-Operator#12]
在`RhinoJobReconciler的SetupWithManager`函数里，只写了 `Owns(&kbatchv1.Job{})` 没有 Pod ，所以 Pod 的状态改变不会*直接*触发这里的 RhinoJob 的 Reconcile 逻辑执行。@chichi321 看到的现象，实际上是因为Pod里的某些状态（Spec和Status里的某些字段的值）变化会导致Job的状态变化，从而触发 RhinoJob 的 Reconcile 逻辑执行。
Pod的状态里字段很多，不是每一个都会导致这个Reconcile函数执行。

**Comment by LI-Mingyu** [comment]
目前还没看到直接 watch pods 状态的必要性
