### ISSUE TITLE
任务中止时再次提交导致报错

### ISSUE THREAD

**Issue by chichi321** [OpenRHINO/RHINO-Operator#26]
当上一个任务处于terminating时，提交同样的任务，会导致触发reconcile逻辑，生成worker pod导致报错

**Comment by chichi321** [comment]
![image](https://user-images.githubusercontent.com/40471189/219292456-01efd929-ead2-4b3c-aff8-fae5f5529f3d.png)

**Comment by LI-Mingyu** [comment]
Maybe naming the K8s jobs with resource hashes can solve this problem. When a K8s deployment creates pods, it uses 'replica set hash' and 'pod hash' to name the pods. We can do something similar.

**Comment by LI-Mingyu** [comment]
Actually we use UID instead of hashes, as in PR #31
