### ISSUE TITLE
mpi "controller" 名称易导致误解

### ISSUE THREAD

**Issue by LI-Mingyu** [OpenRHINO/RHINO-Operator#6]
目前把mpi主控叫做controller job和controller pod，这容易和operator的controller、controller manager混淆。

**Comment by LI-Mingyu** [comment]
我看了 kubeflow 的 mpijob ，它管这个叫 launcher ，我们是不是也叫这个？还是另外在想一个名字？
<img width="457" alt="image" src="https://user-images.githubusercontent.com/20229719/211824192-819011b4-96a7-437c-b1b9-cd31c08df2d3.png">

**Comment by TimeSea05** [comment]
openmpi 文档中的一段：[链接](https://www.open-mpi.org/doc/current/man1/mpiexec.1.php)
mpirun --host node1 ./a.out
***launches*** a number of processes equal to the number of cores on node node1

构建镜像dockerfile中的一段命令：[链接](https://c8s9wpsorl.feishu.cn/docx/doxcn7OP4K8EN2qVrXXTIyXhK6g)
// 在master上以手动模式运行
mpiexec -***launcher*** manual -disable-hostname-propagation -hosts 0,1 ./mpi_hello

感觉用launcher确实比较合适，老师如果没什么问题的话，我马上改一下，提一个PR
