### ISSUE TITLE
pod 启动时间过长

### ISSUE THREAD

**Issue by chichi321** [OpenRHINO/RHINO-Operator#8]
在默认启动项的minikube测试环境中，使用operator启动mpi主控和worker pod时ContainerCreating时间约为3s左右，并且在主控pod running后还需要等待约2s的时间才能ready。与此对比，直接用kubectl apply提交同样的pod整个过程耗时不到2s。

推测的原因可能是默认的测试环境资源较少导致的卡顿，需要进行进一步的测试。

**Comment by chichi321** [comment]
使用rhino-cli run命令提交job，当np指定为4时，operator生成的主控pod无法通过就绪状态检查，会一直处于unready状态

**Comment by chichi321** [comment]
经过对launcher pod的日志观察，在上述情况中，MPI以manual的启动方式，在np>4时需要经过较长时间才能在容器内输出初始化信息，导致就绪状态检查失败；相比之下，使用yaml文件提交的同样的launcher job可以在两秒内完成所有的初始化过程。

**Comment by chichi321** [comment]
启动时两处卡顿位置：
![image](https://user-images.githubusercontent.com/40471189/223295173-96fe59a3-30ab-45b6-9bd0-d102df42291f.png)
![image](https://user-images.githubusercontent.com/40471189/223295245-1eb18c04-bdac-4c86-ac89-ac4d29611f9b.png)

**Comment by LI-Mingyu** [comment]
最终发现，在命令
```
mpirun -launcher manual -verbose -disable-hostname-propagation -hosts '0, 1, 2, 3' ./mpi-func 
```
当 -hosts 参数中有空格时，在某些情况下，可能导致launcher启动非常慢
